---
title: "stateQTI_init"
output: html_document
date: "2024-05-06"
---

# Purpose

We initalize the state-level quantile tracking's learning rate and scores. 

```{r}
source("assets_update/data_load.R")
source("assets_update/unconstrained_state_level_big_lag.R")
source("assets_update/unconstrained_national_level_big_lag.R")
```


```{r}
gammas = signif(seq(0, 0.0625, length.out = 25), 3)
vl = 2; cadence = 30
window_date = as.Date("2021-04-01")
version = as.Date(window_date + 1)
miscover_lvl = 0.4; lower_lvl = miscover_lvl/2; upper_lvl = 1-miscover_lvl/2

# Every day we recieve updated features 
train_end = window_date - vl * cadence 
# Prevent intersection with previous test
test_start = window_date + 1 
test_start = as.Date(test_start, "1970-01-01")

# state level val frame 
state_val_frame = state_produce_fv(gammas, train_end, version)


state_val_gamma = state_val_frame %>%
  group_by(geo_value, gamma) %>%
  summarise(MAE = mean(abs(.resid))) %>%
  mutate(Min = min(MAE)) %>%
  filter(MAE == Min) %>%
  select(geo_value, gamma)

state_lr_frame = state_val_frame %>%
  select(geo_value, time_value, .resid, .fitted) %>%
  group_by(geo_value) %>%
  rename(resid = .resid) %>%
  filter(resid == max(resid)) %>%
  mutate(score = resid / max(.fitted, 1)) %>%
  mutate(lr = 0.1 * score) %>%
  select(geo_value, lr)


tmp_state_gamma = state_val_gamma %>%
    rename(opt_g = gamma)

state_score_frame = state_val_frame %>%
  inner_join(tmp_state_gamma, by = "geo_value") %>%
  filter(gamma == opt_g) %>%
  select(-opt_g) %>%
  rename(resid = .resid) %>%
  # Dampening: Cap the minimum of dampening to be 1
  # This is roughly 60 quantile of the smallest hosp rate of a
  # given state 
  # Some subtlety, the conformal interval is defined as values that is
  # less than a certain quantile of the score 
  mutate(d_t = pmax(abs(.fitted), 1)) %>%
  mutate(lower_e_t = -resid/d_t) %>%
  mutate(upper_e_t = resid / d_t) %>%
  summarise(lower_score = pmax(0, quantile(lower_e_t, probs = 1-miscover_lvl/2)),
            upper_score = pmax(0, quantile(upper_e_t, probs = 1-miscover_lvl/2)))

saveRDS(state_lr_frame, file = "assets_QTI/state_lr_frame.RDS")
saveRDS(state_score_frame, file = "assets_QTI/state_score_frame.RDS")

```




