---
title: "quantile_init"
output: html_document
date: "2024-04-28"
---

# Purpose

Investigate intialization of scores and learning rate of our quantile tracking alg.


```{r, message=FALSE}
source("assets_update/data_load.R")
source("assets_update/unconstrained_state_level_big_lag.R")
source("assets_update/unconstrained_national_level_big_lag.R")
```

# Plot all hosp
# Plot all hosp
```{r}
cbPalette = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442",
              "#0072B2", "#D55E00", "#CC79A7")
fills = c("Actual Hospitalizations" = cbPalette[1], "Nowcasts" = cbPalette[6])
cols = c("Nowcasts" = cbPalette[6])
states = unique(labels_hosp$geo_value)


for (s in states) {
  data_state = labels_hosp %>%
    filter(geo_value == s) %>%
    filter(time_value <= as.Date("2021-12-01"))
  
  p1 = ggplot(data_state, aes(x = time_value, y = GT)) +
    geom_bar(stat = "identity", aes(fill = "Actual Hospitalizations"), alpha = 0.7) +
    scale_color_manual(name = "", values = fills) +
    scale_fill_manual(name = "", values = fills) +
    scale_x_date(date_breaks = "1 month", expand = c(0.01, 0.05),
                 labels = scales::label_date_short()) +
    xlab("Date") +
    ylab("Hospitalization rate") +
    theme_bw() +
    theme(legend.position = "bottom") +
    ggtitle(paste0(toupper(s), ", actual hosp rate"))
    
  print(p1)
  
}

# dev.off()
```

# Compute the validation frame at the first dump date, 2021/04/01
```{r}
miscover_lvl = 0.4
gammas = signif(seq(0, 0.0625, length.out = 25), 3)
alphas = signif(seq(0, 1, length.out = 51))


cadence = 30
offset = 120
vl = 2
sf = "relative"
window_date = as.Date("2021-04-01")
train_end = window_date - vl * cadence 
# Prevent intersection with previous test
test_start = window_date + 1 
test_start = as.Date(test_start, "1970-01-01")

# Don't see new labels, but see updated features
version = window_date + 1
version = as.Date(version, "1970-01-01")

state_val_frame = state_produce_fv(gammas, train_end, version)
state_val_gamma = state_val_frame %>%
  group_by(geo_value, gamma) %>%
  summarise(MAE = mean(abs(.resid))) %>%
  mutate(Min = min(MAE)) %>%
  filter(MAE == Min) %>%
  select(geo_value, gamma)


state_val_gamma = state_val_frame %>%
  group_by(geo_value, gamma) %>%
  summarise(MAE = mean(abs(.resid))) %>%
  mutate(Min = min(MAE)) %>%
  filter(MAE == Min) %>%
  select(geo_value, gamma)

tmp_state_gamma = state_val_gamma %>%
  rename(opt_g = gamma)

```



# Discrepency in scores using nowcasts vs GT
```{r}
state_score_frame = state_val_frame %>%
  inner_join(tmp_state_gamma, by = "geo_value") %>%
  filter(gamma == opt_g) %>%
  select(-opt_g) %>%
  mutate(resid = abs(.resid)) %>%
  # Dampening: Cap the minimum of dampening to be 1
  # This is roughly 60 quantile of the smallest hosp rate of a
  # given state 
  mutate(d_t = pmax(abs(.fitted), 0.1)) %>%
  mutate(ested_et = resid / d_t) %>%
  mutate(true_et = resid / GT) %>%
  summarise(est_score = quantile(ested_et, probs = 1 - miscover_lvl),
            true_score = quantile(true_et, probs = 1 - miscover_lvl))


state_lr_frame = state_val_frame %>%
  select(geo_value, time_value, GT, .resid) %>%
  group_by(geo_value) %>%
  mutate(resid = abs(.resid)) %>%
  select(-.resid) %>%
  filter(resid == max(resid))

```

