---
title: "ana_uncon_mixed"
output: html_document
date: "2023-05-22"
---

# Purpose

Figure 9, 10


# Read data

```{r}
library(assertr)
library(comprehenr)
library(epidatr)
library(epiprocess)
library(broom)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggnewscale)
library(vroom)
library(simplecolors)
library(ggpubr)
library(eply)
library(colorspace)
```

# Big Lag

```{r}
us_pop = covidcast::state_census %>%
          select(ABBR, POPESTIMATE2019) %>%
          rename(geo_value = ABBR) %>%
          rename(pop = POPESTIMATE2019) %>%
          mutate(geo_value = tolower(geo_value)) %>%
          filter(!geo_value %in% c("as", "gu", "mp", "pr", "vi"))



bl_before_2023 = read.csv("../../predictions/oneshot_omicron.csv") %>%
  inner_join(us_pop, by = "geo_value") %>%
  filter(time_value >= as.Date("2021-12-01")) %>%
  mutate(issue_date = as.Date(issue_date),
         time_value = as.Date(time_value)) %>%
  mutate(backcast_lag = as.numeric(issue_date - time_value)) %>%
  filter(backcast_lag <= 10) %>%
  rowwise() %>%
  mutate(state_fit = max(0, state_fit)) %>%
  mutate(mixed_pred = max(0, mixed_pred)) %>%
  mutate(national_fit = max(0, national_fit)) %>%
  mutate(GT_norm_back = GT * pop / 10^5) %>%
  mutate(state_norm_back = state_fit * pop / 10^5) %>%
  mutate(mixed_norm_back = mixed_pred * pop / 10^5) %>%
  mutate(national_norm_back = national_fit * pop / 10^5) %>%
  select(geo_value, time_value, issue_date, backcast_lag, optimal, staleness, 
         GT, state_fit, mixed_pred, national_fit, GT_norm_back, state_norm_back,
         mixed_norm_back, national_norm_back)


bl_after_2023 = read.csv("../../predictions/oneshot_2023.csv") %>%
  inner_join(us_pop, by = "geo_value") %>%
  filter(issue_date >= as.Date("2022-12-26")) %>%
  filter(time_value >= as.Date("2022-12-26")) %>%
  mutate(issue_date = as.Date(issue_date),
         time_value = as.Date(time_value)) %>%
  mutate(backcast_lag = as.numeric(issue_date - time_value)) %>%
  filter(backcast_lag <= 10) %>%
  rowwise() %>%
  mutate(state_fit = max(0, state_fit)) %>%
  mutate(mixed_pred = max(0, mixed_pred)) %>%
  mutate(national_fit = max(0, national_fit)) %>%
  mutate(GT_norm_back = GT * pop / 10^5) %>%
  mutate(state_norm_back = state_fit * pop / 10^5) %>%
  mutate(mixed_norm_back = mixed_pred * pop / 10^5) %>%
  mutate(national_norm_back = national_fit * pop / 10^5) %>%
  select(geo_value, time_value, issue_date, backcast_lag, optimal, staleness, 
         GT, state_fit, mixed_pred, national_fit, GT_norm_back, state_norm_back,
         mixed_norm_back, national_norm_back)



bl_oneshot_preds = rbind(bl_before_2023, bl_after_2023)



bl_oneshot_mixed = bl_oneshot_preds %>%
  inner_join(us_pop, by = "geo_value") %>%
  filter(time_value >= as.Date("2021-12-01")) %>%
  mutate(issue_date = as.Date(issue_date),
         time_value = as.Date(time_value)) %>%
  mutate(backcast_lag = as.numeric(issue_date - time_value)) %>%
  filter(backcast_lag == 5) %>%
  rowwise() %>%
  mutate(mixed_pred = max(0, mixed_pred)) %>%
  mutate(GT_norm_back = GT * pop / 10^5) %>%
  mutate(pred_norm_back = mixed_pred * pop / 10^5) %>%
  select(geo_value, time_value, issue_date, backcast_lag, optimal, staleness, 
         GT, mixed_pred, GT_norm_back, pred_norm_back)


bl_oneshot_state = bl_oneshot_preds %>%
  inner_join(us_pop, by = "geo_value") %>%
  filter(time_value >= as.Date("2021-12-01")) %>%
  mutate(issue_date = as.Date(issue_date),
         time_value = as.Date(time_value)) %>%
  mutate(backcast_lag = as.numeric(issue_date - time_value)) %>%
  filter(backcast_lag == 5) %>%
  rowwise() %>%
  mutate(state_fit = max(0, state_fit)) %>%
  mutate(GT_norm_back = GT * pop / 10^5) %>%
  mutate(pred_norm_back = state_fit * pop / 10^5) %>%
  select(geo_value, time_value, issue_date, backcast_lag, optimal, staleness, 
         GT, state_fit, GT_norm_back, pred_norm_back)


bl_oneshot_national = bl_oneshot_preds %>%
  inner_join(us_pop, by = "geo_value") %>%
  filter(time_value >= as.Date("2021-12-01")) %>%
  mutate(issue_date = as.Date(issue_date),
         time_value = as.Date(time_value)) %>%
  mutate(backcast_lag = as.numeric(issue_date - time_value)) %>%
  filter(backcast_lag == 5) %>%
  rowwise() %>%
  mutate(national_fit = max(0, national_fit)) %>%
  mutate(GT_norm_back = GT * pop / 10^5) %>%
  mutate(pred_norm_back = national_fit * pop / 10^5) %>%
  select(geo_value, time_value, issue_date, backcast_lag, optimal, staleness, 
         GT, national_fit, GT_norm_back, pred_norm_back)
```





# State Level Nowcasts

```{r}
fills = c("Actual Hospitalizations" = "#8B8B8B")
colrs = c("Mixed Model" = "#86B875", "State-level" = "#E495A5",
          "National" = "#7DB0DD")

for (state in unique(bl_oneshot_mixed$geo_value)) {
  

  
  data_state = bl_oneshot_state %>%
    filter(geo_value == state)
  
  data_mixed = bl_oneshot_mixed %>%
    filter(geo_value == state)
  
  data_national = bl_oneshot_national %>%
    filter(geo_value == state)
  
  p1 = ggplot(data_state, aes(x = time_value, y = GT_norm_back)) +
    geom_bar(stat = "identity", aes(fill = "Actual Hosptializations")) +
    scale_x_date(date_labels = "%b", date_breaks = "1 month", expand = c(0.01, 0.05)) +
    xlab("Date") +
    ylab("Hosptializations") +
    geom_path(aes(x = time_value, y = pred_norm_back, color = "State-level"),
              size = 1) +
    geom_path(data = data_mixed,
              aes(x = time_value, y = pred_norm_back, color = "Mixed Model"),
              size = 1) +
    geom_path(data = data_national, 
              aes(x = time_value, y = pred_norm_back, color = "National"), 
              size = 1) +
    scale_fill_manual(name = "", values = fills) +
    scale_color_manual(name = "", values = colrs) +
    theme(legend.position = "bottom") +
    ggtitle(paste0(toupper(state), " , Backcast at lag 5 from Oneshot, Different Model"))
  
  suppressWarnings(print(p1))
  
}
```





```{r, fig.width=8}
fills = c("Actual Hospitalizations" = "#8B8B8B")
colrs = c("Mixed Model" = "#86B875", "State-level" = "#E495A5",
          "National" = "#7DB0DD")

sl = c("ca", "ny")
pl = c()


for (state in sl) {
  
  
  data_state = bl_oneshot_state %>%
    filter(geo_value == state)
  
  data_mixed = bl_oneshot_mixed %>%
    filter(geo_value == state)
  
  data_national = bl_oneshot_national %>%
    filter(geo_value == state)
  
  p1 = ggplot(data_state, aes(x = time_value, y = GT_norm_back)) +
    geom_bar(stat = "identity", aes(fill = "Actual Hosptializations")) +
    scale_x_date(date_breaks = "1 month", expand = c(0.01, 0.05),
                 labels = scales::label_date_short()) +
    xlab("Date") +
    ylab("Hosptializations") +
    scale_y_continuous(n.breaks = 6) +
    geom_path(aes(x = time_value, y = pred_norm_back, color = "State-level"),
              size = 1) +
    geom_path(data = data_mixed,
              aes(x = time_value, y = pred_norm_back, color = "Mixed Model"),
              size = 1) +
    geom_path(data = data_national, 
              aes(x = time_value, y = pred_norm_back, color = "National"), 
              size = 1) +
    scale_fill_manual(name = "", values = fills) +
    scale_color_manual(name = "", values = colrs) +
          theme(legend.position = "bottom", plot.title = element_text(size = 18),
            legend.text = element_text(size = 16)) +
    ggtitle(paste0(toupper(state), ", backcast at lag 5, no update period"))
  
  pl = c(pl, list(p1))
  
  suppressWarnings(print(p1))
  
}

ggarrange(plotlist = pl, nrow = 2, common.legend = TRUE, legend = "bottom")
ggsave("holdout_mixed_big.pdf", width = 12, height = 9, dpi = 320)
```


```{r, fig.width=8}
sl = c("ky", "vt")
pl = c()


for (state in sl) {
  

  data_state = bl_oneshot_state %>%
    filter(geo_value == state)
  
  data_mixed = bl_oneshot_mixed %>%
    filter(geo_value == state)
  
  data_national = bl_oneshot_national %>%
    filter(geo_value == state)
  
  p1 = ggplot(data_state, aes(x = time_value, y = GT_norm_back)) +
    geom_bar(stat = "identity", aes(fill = "Actual Hosptializations")) +
    scale_x_date(date_breaks = "1 month", expand = c(0.01, 0.05),
                 labels = scales::label_date_short()) +
    scale_y_continuous(n.breaks = 6) +
    xlab("Date") +
    ylab("Hosptializations") +
    geom_path(aes(x = time_value, y = pred_norm_back, color = "State-level"),
              size = 1) +
    geom_path(data = data_mixed,
              aes(x = time_value, y = pred_norm_back, color = "Mixed Model"),
              size = 1) +
    geom_path(data = data_national, 
              aes(x = time_value, y = pred_norm_back, color = "National"), 
              size = 1) +
    scale_fill_manual(name = "", values = fills) +
    scale_color_manual(name = "", values = colrs) +
          theme(legend.position = "bottom", plot.title = element_text(size = 18),
            legend.text = element_text(size = 16)) +
    ggtitle(paste0(toupper(state), ", backcast at lag 5, no update period"))
  
  pl = c(pl, list(p1))
  
  suppressWarnings(print(p1))
}

ggarrange(plotlist = pl, nrow = 2, common.legend = TRUE, legend = "bottom")

# ggsave("holdout_mixed_smaller.pdf", width = 12, height = 9, dpi = 320)

```

# Necessity of outputting predictions from all 3

```{r, fig.width=8}
sl = c("al", "ms")
pl = c()


for (state in sl) {
  

  data_state = bl_oneshot_state %>%
    filter(geo_value == state)
  
  data_mixed = bl_oneshot_mixed %>%
    filter(geo_value == state)
  
  data_national = bl_oneshot_national %>%
    filter(geo_value == state)
  
  p1 = ggplot(data_state, aes(x = time_value, y = GT_norm_back)) +
    geom_bar(stat = "identity", aes(fill = "Actual Hosptializations")) +
    scale_x_date(date_labels = "%b", date_breaks = "1 month",
                 labels = scales::label_date_short()) +
    xlab("Date") +
    ylab("Hosptializations") +
    geom_path(aes(x = time_value, y = pred_norm_back, color = "State-level"),
              size = 1) +
    geom_path(data = data_mixed,
              aes(x = time_value, y = pred_norm_back, color = "Mixed Model"),
              size = 1) +
    geom_path(data = data_national, 
              aes(x = time_value, y = pred_norm_back, color = "National"), 
              size = 1) +
    scale_fill_manual(name = "", values = fills) +
    scale_color_manual(name = "", values = colrs) +
    theme(legend.position = "bottom") +
    ggtitle(paste0(toupper(state), " , Nowcasts during No Update Period"))
  
  pl = c(pl, list(p1))
  
  suppressWarnings(print(p1))
}

ggarrange(plotlist = pl, nrow = 2, common.legend = TRUE, legend = "bottom")

```


