---
title: "vis_back_hold_mixed_national"
author: "Xueda Shen, xs2"
date: "2023-08-31"
output: html_document
---

# Purpose

We plot nowcasts  from different models


# Read data

```{r}
library(assertr)
library(comprehenr)
library(epidatr)
library(epiprocess)
library(broom)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggnewscale)
library(vroom)
library(simplecolors)
library(ggpubr)
library(eply)
library(colorspace)
```

# Big Lag

```{r}
bl_uncon_pred = readRDS("../RDS/bl_uncon_pred.rds")
```

# Plot CA NY KY VT

```{r, fig.width=12}
gl = c("ca", "ny", "ky", "vt")
pl = c()

cbPalette = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442",
              "#0072B2", "#D55E00", "#CC79A7")

fills = c("Reported hospitalizations" = cbPalette[1])
colrs = c("Mixed model" = cbPalette[4], "State-level model" = cbPalette[3])

for (state in gl) {
  data = bl_uncon_pred %>%
    filter(geo_value == state)
  
  p1 = ggplot(data, aes(x = time_value, y = GT_norm_back)) +
    geom_bar(stat = "identity", aes(fill = "Reported hospitalizations"), alpha = 0.7) +
    geom_line(aes(x = time_value, y = mixed_fit_back, color = "Mixed model"), 
              linewidth = 0.75) +
    geom_line(aes(x = time_value, y = state_fit_back, color = "State-level model"), 
              linewidth = 0.75, linetype = 2) +
    scale_x_date(date_breaks = "1 month", expand = c(0.01, 0.05),
                 labels = scales::label_date_short()) +
    geom_vline(data = tibble(
      x = seq.Date(as.Date("2021-04-01"),
                   as.Date("2021-12-01"), by = "month")), 
      aes(xintercept = x), linewidth = 0.5, linetype = 2, col = cbPalette[2]) +
    xlab("Date") +
    ylab("COVID-19 hospitalizations") +
    scale_color_manual(name = "", values = colrs) +
    scale_fill_manual(name = "", values = fills) +
    labs(title = paste("Hospitalization nowcasts in", toupper(state))) +
    new_scale_color() + 
    theme(legend.position = "bottom", 
          plot.title = element_text(size = 12),
          legend.text = element_text(size = 11)) + theme_bw()
    
  pl = c(pl, list(p1))
}

ggarrange(plotlist = pl[-2], nrow = 3, common.legend = TRUE, legend = "bottom")
ggsave("../../plots/section_3/monthly_update_examples.pdf", width = 8, height = 9)

ggarrange(plotlist = pl[2], nrow = 1, common.legend = TRUE, legend = "bottom")
ggsave("../../plots/section_3/monthly_update_failure.pdf", width = 8, height = 3.25)
```