---
title: "err_stateonly_v_mixed"
author: "Xueda Shen, xs2"
date: "2023-08-23"
output:
  html_document: default
  pdf_document: default
---

We plot figure 3 and 4 in this document. 

# Read data

```{r}
library(tidyverse)
library(ggnewscale)
library(vroom)
library(ggpubr)
library(colorspace)
```

```{r}
mae_state_count = readRDS("../RDS/mae_state_count.rds")
mae_mixed_count = readRDS("../RDS/mae_mixed_count.rds")
mae_national_count = readRDS("../RDS/mae_national_count.rds")

mae_state_rate = readRDS("../RDS/mae_state_rate.rds")
mae_mixed_rate = readRDS("../RDS/mae_mixed_rate.rds")
mae_national_rate = readRDS("../RDS/mae_national_rate.rds")

pve_state = readRDS("../RDS/state_PVE.rds")
pve_mixed = readRDS("../RDS/mixed_PVE.rds")
pve_national = readRDS("../RDS/national_PVE.rds")
```

```{r}
cbPalette = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442",
              "#0072B2", "#D55E00", "#CC79A7")

vals = c("Geo-pooled model" = cbPalette[7], 
         "Mixed model" = cbPalette[4], 
         "State-level model" = cbPalette[3])

alpha = 0.4

p1 = ggplot() +
  geom_line(data = mae_national_count, aes(x = backcast_lag,
            y = nMAE, color = "Geo-pooled model"), linewidth = 1) +
  geom_ribbon(data = mae_national_count, aes(x = backcast_lag,
            ymin = nMAE - se, ymax = nMAE + se, fill = "Geo-pooled model"),
            linewidth = 1, alpha = alpha) +
  geom_line(data = mae_mixed_count, aes(x = backcast_lag, y = mMAE,
                color = "Mixed model"), linewidth = 1) +
  geom_ribbon(data = mae_mixed_count, aes(x = backcast_lag,
            ymin = mMAE - se, ymax = mMAE + se,fill = "Mixed model"),
            linewidth = 1, alpha = alpha) +
  geom_line(data = mae_state_count,
            aes(x = backcast_lag, y = sMAE, color = "State-level model"),
            linewidth = 1) +
  geom_ribbon(data = mae_state_count, 
              aes(x = backcast_lag, ymin = sMAE - se,
                  ymax= sMAE + se, fill = "State-level model"),
              alpha = alpha) +
  scale_color_manual(name = "", values = vals) +
  scale_fill_manual(name = "", values = vals) +
  scale_x_continuous(n.breaks = 6) +
  xlab("Backcast lag") +
  ylab("MAE (hospitalization count)") +
  theme(legend.text = element_text(size = 11),
        axis.title = element_text(size = 11),
        plot.title = element_text(size = 12)) + theme_bw()

p2 = ggplot() +  
  geom_line(data = mae_national_rate, aes(x = backcast_lag, 
          y = n_MAER, color = "Geo-pooled model"), linewidth = 1) +
  geom_ribbon(data = mae_national_rate, aes(x = backcast_lag,
            ymin = n_MAER - se, ymax = n_MAER + se, fill = "Geo-pooled model"),
            linewidth = 1, alpha = alpha) +
  geom_line(data = mae_mixed_rate, aes(x = backcast_lag, y = m_MAER,
                color = "Mixed model"), linewidth = 1) +
  geom_ribbon(data = mae_mixed_rate, aes(x = backcast_lag,
            ymin = m_MAER - se, ymax = m_MAER + se, fill = "Mixed model"),
            linewidth = 1, alpha = alpha) +
  geom_line(data = mae_state_rate,
            aes(x = backcast_lag, y = s_MAER, color = "State-level model"), 
            linewidth = 1) +
  geom_ribbon(data = mae_state_rate,
              aes(x = backcast_lag, ymin = s_MAER - se, 
                  ymax= s_MAER + se, fill = "State-level model"), 
              alpha = alpha) +
  scale_color_manual(name = "", values = vals) +
  scale_fill_manual(name = "", values = vals) +
  scale_x_continuous(n.breaks = 6) +
  xlab("Backcast lag") +
  ylab("MAE (hospitalization rate)") +
  theme(legend.text = element_text(size = 11),
        axis.title = element_text(size = 11),
        plot.title = element_text(size = 12)) + 
  theme_bw()

ggarrange(p1, p2, nrow = 1, common.legend = TRUE, legend = "bottom")
ggsave("../../plots/section_3/monthly_update_mae.pdf", width = 9, height = 4.5)
```
