---
title: "vis_mixed_holdin"
output: html_document
date: "2023-10-10"
---

# Purpose

We plot predictions from mixed model at backcast lag {0, 5, 10} during the monthly update period.


# Read data

```{r}
library(assertr)
library(comprehenr)
library(epidatr)
library(epiprocess)
library(broom)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggnewscale)
library(vroom)
library(simplecolors)
library(ggpubr)
library(eply)
library(colorspace)
```


# Big Lag

```{r}
us_pop = covidcast::state_census %>%
          select(ABBR, POPESTIMATE2019) %>%
          rename(geo_value = ABBR) %>%
          rename(pop = POPESTIMATE2019) %>%
          mutate(geo_value = tolower(geo_value)) %>%
          filter(!geo_value %in% c("as", "gu", "mp", "pr", "vi"))


bl_mixed_now = read.csv("../predictions/bl_versioned_hhs_mixed.csv") %>%
  inner_join(us_pop, by = "geo_value") %>%
  filter(time_value <= as.Date("2021-12-01")) %>%
  mutate(issue_date = as.Date(issue_date),
         time_value = as.Date(time_value)) %>%
  mutate(backcast_lag = as.numeric(issue_date - time_value)) %>%
  filter(backcast_lag == 0) %>%
  rowwise() %>%
  mutate(mixed_pred = max(0, mixed_pred)) %>%
  mutate(GT_norm_back = GT * pop / 10^5) %>%
  mutate(pred_norm_back = mixed_pred * pop / 10^5) %>%
  select(geo_value, time_value, issue_date, backcast_lag, optimal, staleness, 
         GT, mixed_pred, GT_norm_back, pred_norm_back)


bl_mixed_5 = read.csv("../predictions/bl_versioned_hhs_mixed.csv") %>%
  inner_join(us_pop, by = "geo_value") %>%
  filter(time_value <= as.Date("2021-12-01")) %>%
  mutate(issue_date = as.Date(issue_date),
         time_value = as.Date(time_value)) %>%
  mutate(backcast_lag = as.numeric(issue_date - time_value)) %>%
  filter(backcast_lag == 5) %>%
  rowwise() %>%
  mutate(mixed_pred = max(0, mixed_pred)) %>%
  mutate(GT_norm_back = GT * pop / 10^5) %>%
  mutate(pred_norm_back = mixed_pred * pop / 10^5) %>%
  select(geo_value, time_value, issue_date, backcast_lag, optimal, staleness, 
         GT, mixed_pred, GT_norm_back, pred_norm_back)


bl_mixed_10 = read.csv("../predictions/bl_versioned_hhs_mixed.csv") %>%
  inner_join(us_pop, by = "geo_value") %>%
  filter(time_value <= as.Date("2021-12-01")) %>%
  mutate(issue_date = as.Date(issue_date),
         time_value = as.Date(time_value)) %>%
  mutate(backcast_lag = as.numeric(issue_date - time_value)) %>%
  filter(backcast_lag == 10) %>%
  rowwise() %>%
  mutate(mixed_pred = max(0, mixed_pred)) %>%
  mutate(GT_norm_back = GT * pop / 10^5) %>%
  mutate(pred_norm_back = mixed_pred * pop / 10^5) %>%
  select(geo_value, time_value, issue_date, backcast_lag, optimal, staleness, 
         GT, mixed_pred, GT_norm_back, pred_norm_back)


```



# State Level Nowcasts

```{r}
fills = c("Actual Hospitalizations" = "#8B8B8B")
colrs = c("Nowcasts" = "#86B875", "Lag 5" = "#E495A5",
          "Lag 10" = "#7DB0DD")

pl = c()

for (state in unique(bl_mixed_now$geo_value)) {
  

  
  data_now = bl_mixed_now %>%
    filter(geo_value == state)
  
  data_5 = bl_mixed_5 %>%
    filter(geo_value == state)
  
  data_10 = bl_mixed_10 %>%
    filter(geo_value == state)
  
  p1 = ggplot(data_now, aes(x = time_value, y = GT_norm_back)) +
    geom_bar(stat = "identity", aes(fill = "Actual Hosptializations")) +
    scale_x_date(date_breaks = "1 month", expand = c(0.01, 0.05),
                 labels = scales::label_date_short()) +
    xlab("Date") +
    ylab("Hosptializations") +
    geom_path(aes(x = time_value, y = pred_norm_back, color = "Nowcasts"),
              size = 0.8) +
    geom_path(data = data_5,
              aes(x = time_value, y = pred_norm_back, color = "Lag 5"),
              size = 0.8) +
    geom_path(data = data_10, 
              aes(x = time_value, y = pred_norm_back, color = "Lag 10"), 
              size = 0.8) +
    scale_fill_manual(name = "", values = fills) +
    scale_color_manual(name = "", values = colrs) +
    theme(legend.position = "bottom") +
    ggtitle(paste0(toupper(state), " , Predictions at different backcast lags, mixed model"))
  
  suppressWarnings(print(p1))
  
  pl = append(pl, list(p1))
  
}
```


```{r}
arranged = ggarrange(plotlist = pl, nrow = 3)

# ggexport(arranged, filename = "holdin_back_mixed.pdf")


```

