---
title: "concordence_plots"
output: html_document
date: "2023-05-11"
---

# Purpose

Produce figure 1 in paper, concordance plot between $Y_t$ and $I_t^{(t)}$ and $I_t^{(t + 30)}.$

```{r}
library(assertr)
library(comprehenr)
library(epidatr)
library(epiprocess)
library(broom)
library(tidyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(vroom)
library(simplecolors)
library(ggpubr)
library(eply)
library(colorspace)
```


```{r}
in_raw = vroom("../../versioned_feature/rebuild_inpatient_raww_avg.csv") %>%
          filter(time_value >= as.Date("2020-11-01") & time_value <= as.Date("2021-12-01")) %>%
          filter(issue_date <= as.Date("2022-02-01")) %>%
          filter(!geo_value %in%  c("as", "gu", "mp", "pr", "vi", "fm", "mh")) %>%
          mutate(time_value = as.Date(time_value), issue_date = as.Date(issue_date))  %>%
          mutate(weekly_per = 100 * weekly_in_ratio) %>%
          rename(backcast_lag = lag) %>%
          arrange(geo_value, time_value, issue_date)


labels_hosp = vroom("../../versioned_feature/ground_truth.csv") %>%
                    filter(time_value >= as.Date("2020-11-01") & time_value <= as.Date("2021-12-01")) %>%
                    mutate(time_value = as.Date(time_value)) %>%
                    filter(geo_value != "vi")


dat = in_raw %>%
        full_join(select(labels_hosp, geo_value, time_value, GT),
                   by = c("geo_value", "time_value")) 
```



# Visualize california


```{r}
ca = dat %>% 
  filter(geo_value == "ca") %>%
  filter(time_value >= as.Date("2020-11-01") & time_value <= as.Date("2021-12-01"))

ca_finalized = ca %>%
    filter(issue_date == time_value + 30)

ca_proper = ca %>%
    filter(issue_date == time_value) %>%
    complete(time_value = seq.Date(range(ca_finalized$time_value)[1], 
                                   range(ca_finalized$time_value)[2],
                                   by = "day"))

# Scale hospitalizations and inpatient signal

trans = function(x, from_range, to_range) {
  (x - from_range[1]) / (from_range[2] - from_range[1]) *
    (to_range[2] - to_range[1]) + to_range[1]
}

inpat_range = ca_finalized %>%
  select(weekly_in_ratio) %>%
  range


hosp_range = ca_finalized %>%
  select(GT) %>%
  range




trans = function(x, from_range, to_range) {
  (x - from_range[1]) / (from_range[2] - from_range[1]) *
    (to_range[2] - to_range[1]) + to_range[1]
}

inpat_range = ca_finalized %>%
  select(weekly_in_ratio) %>%
  range


hosp_range = ca_finalized %>%
  select(GT) %>%
  range


# Scale inpatient rate to hosp and vice versa
trans_rate_hosp = function(x) trans(x, inpat_range, hosp_range)
trans_hosp_rate = function(x) trans(x, hosp_range, inpat_range)

vals = c("Actual Hospitalizations" = "#E495A5",
         "Concurrently Versioned Inpatient" = "#7DB0DD",
         "Finalized Inpatient" = "#86B875")

p1 = ggplot(ca_finalized) +
  geom_line(aes(x = time_value, y = GT, color = "Actual Hospitalizations"), size = 1) +
  geom_line(aes(x = time_value, y = trans_rate_hosp(weekly_in_ratio), color = "Finalized Inpatient"), size = 1) +
  geom_line(data = ca_proper, aes(x = time_value, y = trans_rate_hosp(weekly_in_ratio), 
                                  color = "Concurrently Versioned Inpatient"), size = 1) +
  scale_y_continuous(name = "7dav HHS Hospitalization Counts", limits = hosp_range,
                     sec.axis = sec_axis(trans = trans_hosp_rate, 
                                         breaks = scales::pretty_breaks(n = 4),
                                         name = "7dav CHNG Inpatient Claims Ratio")) +
  xlab("Year and Month") +
  scale_color_manual(name = "", values = vals) + 
  scale_x_date(date_breaks = "2 month", date_labels = "%Y-%m") +
  ggtitle("CA, HHS Hospitalization Counts and CHNG Inpatient Claims Signals") +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 14),
        axis.title = element_text(size =14))  

ggarrange(p1)


# ggsave("CA_concord.pdf", plot = p1,width = 12, height = 12 * 9/16, dpi = 320)
```


