---
title: "holdin_corr"
author: "Xueda Shen, xs2"
date: "2023-08-23"
output: html_document
---

# Purpose 

Compute national average of state level correlation of $Y_t$ and $I_{t - l}^{(t)};$ $Y_t$ and $O_{t - l}^{(t)}$

# Read data


```{r}
library(assertr)
library(comprehenr)
library(epidatr)
library(epiprocess)
library(broom)
library(tidyr)
library(dplyr)
library(ggplot2)
library(vroom)
library(simplecolors)
library(ggpubr)
library(eply)
library(colorspace)
```


```{r}
# This is 7 day averaged. Not the most raw
in_raw = vroom("../../versioned_feature/rebuild_inpatient_raww_avg.csv") %>%
          filter(time_value >= as.Date("2020-11-01") & time_value <= as.Date("2021-12-01")) %>%
          filter(issue_date <= as.Date("2022-02-01")) %>%
          filter(!geo_value %in%  c("as", "gu", "mp", "pr", "vi", "fm", "mh")) %>%
          mutate(time_value = as.Date(time_value), issue_date = as.Date(issue_date))  %>%
          mutate(weekly_per = 100 * weekly_in_ratio) %>%
          rename(backcast_lag = lag) %>%
          arrange(geo_value, time_value, issue_date)

out_raw = vroom("../../versioned_feature/padded_outpatient_raw_avg.csv") %>%
            filter(time_value >= as.Date("2020-11-01") & time_value <= as.Date("2021-12-01")) %>%
            filter(issue_date <= as.Date("2022-02-01")) %>%
            filter(!geo_value %in%  c("as", "gu", "mp", "pr", "vi")) %>%
            mutate(time_value = as.Date(time_value), issue_date = as.Date(issue_date)) %>%
            rename(backcast_lag = lag) 

labels_hosp = vroom("../../versioned_feature/ground_truth.csv") %>%
                    filter(time_value >= as.Date("2020-11-01") & time_value <= as.Date("2021-12-01")) %>%
                    mutate(time_value = as.Date(time_value)) %>%
                    filter(geo_value != "vi")


uspop = covidcast::state_census %>%
          select(ABBR, POPESTIMATE2019) %>%
          rename(geo_value = ABBR) %>%
          rename(pop = POPESTIMATE2019) %>%
          mutate(geo_value = tolower(geo_value)) %>%
          slice(., 2:(n() - 4))




dat = in_raw %>%
        filter(time_value <= as.Date("2021-03-31")) %>%
        filter(issue_date == time_value + 30) %>%
        inner_join(select(out_raw, geo_value, time_value, issue_date, weekly_out_ratio),
                   by = c("geo_value", "time_value", "issue_date")) %>%
        inner_join(select(labels_hosp, geo_value, time_value, GT),
                   by = c("geo_value", "time_value")) %>%
        inner_join(uspop, by = "geo_value")



```



# Correlation Plot

```{r}
corr_mat = matrix(nrow = 0, ncol = 4)

for (i in seq(0, 20)) {
  
  
  tr = dat %>%
          group_by(geo_value, time_value) %>%
          select(geo_value, time_value, issue_date, weekly_in_ratio,
                   weekly_out_ratio, GT) %>%
          ungroup() %>%
          group_by(geo_value) %>%
          mutate(in_lagged = lag(weekly_in_ratio, n = i)) %>%
          mutate(out_lagged = lag(weekly_out_ratio, n = i)) %>%
          na.omit()

  
  tmp = tr %>%
          ungroup() %>%
          group_by(geo_value) %>%
          summarise(in_cor = cor(in_lagged, GT),
                    out_cor = cor(out_lagged, GT)) %>%
          mutate(backcast_lag = i)

  corr_mat = rbind(corr_mat, tmp)
  
}


corr_mat = corr_mat %>%
  inner_join(uspop, by = "geo_value") %>%
  mutate(l_pop = log(pop))


corr_national_avg = corr_mat %>%
  ungroup() %>%
  filter(backcast_lag <= 10) %>%
  group_by(backcast_lag) %>%
  summarise(in_avg_cor = mean(in_cor),
            in_se_cor = sd(in_cor) / sqrt(50),
            out_avg_cor = mean(out_cor),
            out_se_cor = sd(out_cor) / sqrt(50))


save(corr_national_avg, file = "../RDS/national_avg_corr.Rdata")

```



