---
title: "ny_tmp"
output: html_document
date: "2023-12-14"
---


```{r}
source("assets_update/data_load.R")
source("assets_update/unconstrained_state_level_big_lag.R")
source("assets_update/unconstrained_national_level_big_lag.R")
dat = dat %>% filter(geo_value == "ny")

```



```{r}
"
Code for mixing between unconstrained state level and unconstrained national level
"

gammas = signif(seq(0, 0.0625, length.out = 25), 3)
alphas = signif(seq(0, 1, length.out = 51))

cadence = 30
offset = 120
vl = 2



back_2 = c()
val_frame = c()
val_gamma = c()

max_lag = 19

state_model_coef = c()
national_model_coef = c()


dump_dates = c(as.Date("2021-05-01"), as.Date("2021-06-01")) 

dump_dates = dump_dates - 1

for (window_date in dump_dates) {
  
  
  # The part where we change things
  # Here we will iterate through time points in prediction set + 30 days
  # This means for all `time_value` in the test set, we would have `backcast_lag` 
  # up to 30
  # On day T before end of month, we will produce nowcast \hat{Y}_{T}^{(T)} and a 
  # bunch of trailing nowcasts \hat{Y}_{< T}^{(T)}
  # If at end of month, get feature for whole month with newer version 
  # (`issue_date`) after end of month
  # `window_date`: last observation before test set 
  # that can be used to fit the model
  # So `window_date` contains 60 days of validation data
  
  max_date = as.numeric(as.Date("2022-07-31") - window_date) - 1
  print(max_date)
  
  
  if (max_date == 0) {
    
    break
    
  }
  
  # Iterating through test set 
  # Adhering to hypothetical that we are not looking at
  # predictions with backcast_lag = 30 for the entirety 
  # of test set
  for (i in seq(1, 30)) {
    
    
    # In each day in test, we first calibrate
    # Then produce
    
    # Preparing for calibrating FV here.
    # You are not observing new labels of hosp
    # So you are training with updated versions of features
    
    # Subsetting so that we dont see val set 
    train_end = window_date - vl * cadence 
    # Prevent intersection with previous test
    test_start = window_date + 1 
    test_start = as.Date(test_start, "1970-01-01")
    
    # Don't see new labels, but see updated features
    version = window_date + i
    version = as.Date(version, "1970-01-01")
    
    # state level val frame 
    state_val_frame = state_produce_fv(gammas, train_end, version)
    
    # National level val frame 
    national_val_frame = national_produce_fv(gammas, train_end, version)
    
    if (nrow(state_val_frame) == 0) {
      
      break
      
    }
    
    # Make sure test predictions are out of sample
    stopifnot(state_val_frame$time_value <= as.Date(test_start, "1970-01-01"))
    
    
    # Select FV gamma and retrain
    # Two levels: state and national level
    # No more subsetting: `produce_fv` only produces 2 months of FV data
    state_val_gamma = state_val_frame %>%
      group_by(geo_value, gamma) %>%
      summarise(MAE = mean(abs(.resid))) %>%
      mutate(Min = min(MAE)) %>%
      filter(MAE == Min) %>%
      select(geo_value, gamma)
    
    # Check if state gamma is unique
    stopifnot(nrow(state_val_gamma) == length(unique(state_val_gamma$geo_value)))
    
    national_gamma = national_val_frame %>%
      group_by(gamma) %>%
      summarise(MAE = mean(abs(.resid))) %>%
      mutate(Min = min(MAE)) %>%
      filter(MAE == Min) %>%
      select(gamma)
    
    # Refit, this time using all the data, with `window_date` as cutoff
    # State level
    state_train = state_get_train_ar(window_date, version) %>%
      group_by(geo_value) %>%
      merge(state_val_gamma, by = "geo_value")
    
    national_train = national_get_train_ar(window_date, version) %>%
      ungroup() %>%
      mutate(ng = national_gamma$gamma)
    
    
    # We have changed our model to be autoregressive
    state_selected_models = state_train %>%
      group_by(geo_value) %>%
      do(model = lm(GT ~ in_6 + in_13 + in_20 + out_6 + out_13 + out_20, 
                    weights = exp(-gamma * backcast_lag) / max(exp(-gamma * backcast_lag)),
                    data = .))
    
    national_selected_models = lm(GT ~ in_6 + in_13 + in_20 + out_6 + out_13 + out_20, 
                    weights = exp(-ng * backcast_lag) / max(exp(-ng * backcast_lag)),
                    data = national_train)
    
    
    # After selection and retrain, store the models with `geo_value` and `issue_date`
    # It is important to store the RETRAINED coefficents
    state_selected_tmp = state_selected_models %>%
      group_by(geo_value) %>%
      group_modify(~ bind_rows(coef(.$model[[1]]))) %>%
      mutate(issue_date = as.Date(version, "1970-01-01"),
             window_date = window_date)
    
    state_model_coef = rbind(state_model_coef, state_selected_tmp)
    
    # national_selected_tmp = national_selected_models %>%
    #   summarise(~ bind_rows(coef(national_selected_models))) %>%
    #   mutate(issue_date = as.Date(version, "1970-01-01"))
    
    national_model_coef = rbind(national_model_coef, c(national_selected_models$coefficients, 
      as.Date(version, "1970-01-01")))
    
    
    
    
    # Find alphas now
    mixed_val_frame = alpha_fv(alphas, state_val_frame, national_val_frame, state_val_gamma, national_gamma)
    opt_alpha = mixed_val_frame %>%
      group_by(geo_value, alpha) %>%
      summarise(MAE = mean(.resid)) %>%
      mutate(Min = min(MAE)) %>%
      filter(MAE == Min) %>%
      rename(optimal = alpha) %>%
      select(geo_value, optimal)
    
    
    
    state_test = state_get_test_backnow_raw(test_start, version)
    national_test = national_get_test_backnow_raw(test_start, version)
    
    # If not test points at all, next date in test time
    if (nrow(state_test) == 0) {
      next
    }
    
    # Another round of making sure out of sample
    stopifnot(max(state_val_frame$time_value) <= min(state_test$time_value))
    stopifnot(max(state_train$time_value) <= min(state_test$time_value))
    
    # Use inner_join to avoid problems in null data
    # So that you don't actually predict training samples...
    state_test = state_test %>%
      group_by(geo_value) %>%
      nest() %>%
      inner_join(state_selected_models) %>%
      verify(nrow(.) != 0)
    
    national_test = national_test %>%
      mutate(national_fit = predict(national_selected_models, newdata = .)) %>%
      verify(nrow(.) != 0)
    

    state_Tested = state_test %>%
      do(augment(.$model[[1]], newdata = .$data[[1]])) %>%
      rename(state_fit = .fitted) %>%
      select(geo_value, time_value, issue_date, state_fit, GT)
    
    national_Tested = national_test %>%
      select(geo_value, time_value, issue_date, national_fit)
    
    # Book-keeping gamma for tracking effective sample size 
    state_gamma  = state_val_gamma %>%
      rename(state_optimal_gamma = gamma)
    
    
    
    Tested = state_Tested %>%
      inner_join(national_Tested, by = c("geo_value", "time_value", "issue_date")) %>%
      inner_join(opt_alpha, by = "geo_value") %>%
      # Book-keep gamma for effective sample size calculaiton
      inner_join(state_gamma, by = "geo_value") %>%
      mutate(national_gamma = national_gamma$gamma) %>%
      group_by(geo_value) %>%
      mutate(mixed_pred = optimal * state_fit + (1 - optimal) * national_fit) %>%
      mutate(staleness = as.numeric(time_value - window_date))
    
    
    back_2 = rbind(back_2, Tested)
    
  }
  
  
  
}



# write.csv(back_2, "../predictions/bl_versioned_hhs_mixed.csv", row.names = FALSE)

```


```{r}
state_model_coef = state_model_coef %>%
  filter(geo_value == "ny") %>%
  mutate(window_date = as.Date(window_date))

saveRDS(state_model_coef, "ny_model_coef.rds")




neg_now = back_2 %>%
  filter(time_value == issue_date) %>%
  filter(state_fit < 0)
```


```{r}
ny_train_test_feat = c()


for (i in c(as.Date("2021-05-01"), as.Date("2021-06-01"))) {
  
  for (j in seq(as.Date(i, "1970-01-01"), as.Date(i + 70, "1970-01-01"), by = 1)) {
    

      tmp = state_get_test_backnow_raw(as.Date(i, "1970-01-01"), as.Date(j, "1970-01-01")) %>%
        filter(geo_value == "ny") %>%
        select(geo_value, time_value, issue_date, in_6, in_13, in_20,
           out_6, out_13, out_20, GT)
      ny_train_test_feat = rbind(ny_train_test_feat, tmp)
  
    
  }
  

}


saveRDS(ny_train_test_feat, "ny_train_test_feat.rds")

```

```{r}
ny_feat_may = ny_test_feat %>%
  filter(time_value >= as.Date("2021-05-01") & time_value <= as.Date("2021-05-31"))

ny_may_now = ny_feat_may %>%
  filter(time_value == issue_date)

ny_may_final = ny_feat_may %>%
  filter(issue_date == time_value + 30)

ny_feat_june = ny_test_feat %>%
  filter(time_value >= as.Date("2021-06-01") & time_value <= as.Date("2021-06-30"))


ny_june_now = ny_feat_june %>%
  filter(time_value == issue_date)

ny_june_final = ny_feat_june %>%
  filter(issue_date == time_value + 30)

```


# Real time, inpat

```{r}
ggplot(ny_may_now) +
  geom_path(aes(x = time_value, y = in_6, color = "May"), 
            linewidth = 1) +
  geom_path(data = ny_june_now, aes(x = time_value, y = in_6, color = "June"),
            linewidth = 1) +
  ggtitle("Real time value of in_6")


ggplot(ny_may_now) +
  geom_path(aes(x = time_value, y = in_13, color = "May"), 
            linewidth = 1) +
  geom_path(data = ny_june_now, aes(x = time_value, y = in_13, color = "June"),
            linewidth = 1) +
  ggtitle("Real time value of in_13")

ggplot(ny_may_now) +
  geom_path(aes(x = time_value, y = in_20, color = "May"), 
            linewidth = 1) +
  geom_path(data = ny_june_now, aes(x = time_value, y = in_20, color = "June"),
            linewidth = 1) +
  ggtitle("Real time value of in_20")


ggplot(ny_may_now) +
  geom_path(aes(x = time_value, y = GT, color = "May"), 
            linewidth = 1) +
  geom_path(data = ny_june_now, aes(x = time_value, y = GT, color = "June"),
            linewidth = 1) +
  ggtitle("Hosp in rate")


```


# Real time, outpat

```{r}
ggplot(ny_may_now) +
  geom_path(aes(x = time_value, y = out_6, color = "May"), 
            linewidth = 1) +
  geom_path(data = ny_june_now, aes(x = time_value, y = out_6, color = "June"),
            linewidth = 1) +
  ggtitle("Real time value of out_6")


ggplot(ny_may_now) +
  geom_path(aes(x = time_value, y = out_13, color = "May"), 
            linewidth = 1) +
  geom_path(data = ny_june_now, aes(x = time_value, y = out_13, color = "June"),
            linewidth = 1) +
  ggtitle("Real time value of out_13")



ggplot(ny_may_now) +
  geom_path(aes(x = time_value, y = out_20, color = "May"), 
            linewidth = 1) +
  geom_path(data = ny_june_now, aes(x = time_value, y = out_20, color = "June"),
            linewidth = 1) +
  ggtitle("Real time value of out_20")

```




# Final v versioned



```{r}
ggplot(ny_june_now) +
  geom_path(aes(x = time_value, y = out_6, color = "Now"), 
            linewidth = 1) +
  geom_path(data = ny_june_final, aes(x = time_value, y = out_6, color = "Final"),
            linewidth = 1) +
  ggtitle("June, Real time vs final value of out_6")

ggplot(ny_june_now) +
  geom_path(aes(x = time_value, y = out_13, color = "Now"), 
            linewidth = 1) +
  geom_path(data = ny_june_final, aes(x = time_value, y = out_13, color = "Final"),
            linewidth = 1) +
  ggtitle("June, Real time vs final value of out_13")


ggplot(ny_june_now) +
  geom_path(aes(x = time_value, y = out_20, color = "Now"), 
            linewidth = 1) +
  geom_path(data = ny_june_final, aes(x = time_value, y = out_20, color = "Final"),
            linewidth = 1) +
  ggtitle("June, Real time vs final value of out_20")
```






```{r}
ggplot(ny_may_now) +
  geom_path(aes(x = time_value, y = out_6, color = "Now"), 
            linewidth = 1) +
  geom_path(data = ny_may_final, aes(x = time_value, y = out_6, color = "Final"),
            linewidth = 1) +
  ggtitle("May, Real time vs final value of out_6")
```


```{r}
ny_may_7 = state_get_test_backnow_raw(as.Date("2021-05-01"), as.Date("2021-06-07"))
ny_may_8 = state_get_test_backnow_raw(as.Date("2021-05-01"), as.Date("2021-06-08"))
ny_may_30 = state_get_test_backnow_raw(as.Date("2021-05-01"), as.Date("2021-06-30"))


ny_


```


```{r}
ggplot(ny_may_7) +
  geom_path(aes(x = time_value, y = in_6, color = "June 7"),
            linewidth = 1) +
  geom_path(data = ny_may_8, aes(x = time_value, y = in_6, color = "June 8"),
            linewidth = 1) +
  geom_path(data = ny_may_12, aes(x = time_value, y = in_6, color = "June 12"),
            linewidth = 1) +
  ylab("value") +
  labs(color = "Issue date") +
  ggtitle("Value of in_6, training data")


ggplot(ny_may_7) +
  geom_path(aes(x = time_value, y = in_13, color = "June 7"),
            linewidth = 1) +
  geom_path(data = ny_may_8, aes(x = time_value, y = in_13, color = "June 8"),
            linewidth = 1) +
  geom_path(data = ny_may_12, aes(x = time_value, y = in_13, color = "June 12"),
            linewidth = 1) +
  ylab("value") +
  labs(color = "Issue date") +
  ggtitle("Value of in_13, training data")


ggplot(ny_may_7) +
  geom_path(aes(x = time_value, y = in_20, color = "June 7"),
            linewidth = 1) +
  geom_path(data = ny_may_8, aes(x = time_value, y = in_20, color = "June 8"),
            linewidth = 1) +
  geom_path(data = ny_may_12, aes(x = time_value, y = in_20, color = "June 12"),
            linewidth = 1) +
  ylab("value") +
  labs(color = "Issue date") +
  ggtitle("Value of in_20, training data")


```


```{r}


ggplot(ny_may_7) +
  geom_path(aes(x = time_value, y = out_6, color = "June 7"),
            linewidth = 1) +
  geom_path(data = ny_may_8, aes(x = time_value, y = out_6, color = "June 8"),
            linewidth = 1) +
  geom_path(data = ny_may_12, aes(x = time_value, y = out_6, color = "June 12"),
            linewidth = 1) +
  xlab("Time value") +
  ylab("value") +
  labs(color = "Issue date") +
  ggtitle("Value of out_6, training data")


ggplot(ny_may_7) +
  geom_path(aes(x = time_value, y = out_13, color = "June 7"),
            linewidth = 1) +
  geom_path(data = ny_may_8, aes(x = time_value, y = out_13, color = "June 8"),
            linewidth = 1) +
  geom_path(data = ny_may_12, aes(x = time_value, y = out_13, color = "June 12"),
            linewidth = 1) +
  xlab("Time value") +
  ylab("value") +
  labs(color = "Issue date") +
  ggtitle("Value of out_13, training data")


ggplot(ny_may_7) +
  geom_path(aes(x = time_value, y = out_20, color = "June 7"),
            linewidth = 1) +
  geom_path(data = ny_may_8, aes(x = time_value, y = out_20, color = "June 8"),
            linewidth = 1) +
  geom_path(data = ny_may_12, aes(x = time_value, y = out_20, color = "June 12"),
            linewidth = 1) +
  xlab("Time value") +
  ylab("value") +
  labs(color = "Issue date") +
  ggtitle("Value of out_20, training data")



```




```{r}
trans = function(x, from_range, to_range) {
  (x - from_range[1]) / (from_range[2] - from_range[1]) *
    (to_range[2] - to_range[1]) + to_range[1]
}

out_range = ny_may_12 %>%
  select(out_20) %>%
  range

GT_range = ny_may_12 %>%
  select(GT) %>%
  range

trans_out_hosp = function(x) trans(x, out_range, GT_range)
trans_hosp_out = function(x) trans(x, GT_range, out_range)

ggplot(data = ny_may_12, aes(x = time_value)) +
  geom_line(aes(y = out_20, color = "Issue: June 12"),
            linewidth = 1) +  # Plot out_20
  geom_line(data = ny_may_7, aes(y = out_20, color = "Issue: June 7"),
            linewidth = 1) +
  geom_line(data = ny_june_now, aes(y = out_20, color = "Real time data, June"),
            linewidth = 1) +
  geom_line(aes(y = trans_hosp_out(GT), color = "GT"), linewidth = 1) +  # Plot GT with scaling
  # geom_line(data = ny_june_now, aes(y = trans_hosp_out(GT), color = "GT"), linewidth = 1) +
  scale_y_continuous(
    name = "out_20 scale",
    limits = out_range,
    sec.axis = sec_axis(trans = trans_out_hosp, 
                        name = "GT scale")  # Add secondary axis
  ) +
  labs(title = "Comparison of out_20 and GT over Time",
       x = "Time Value") +
  theme(legend.position = "bottom")
```






```{r}
june_coef = state_model_coef %>%
  filter(window_date >= as.Date("2021-05-31"))



ggplot(june_coef, aes(x = issue_date)) +
  geom_path(aes(y = in_6, color = "in_6"), linewidth = 1) +
  geom_path(aes(y = in_13, color = "in_13"), linewidth = 1) +
  geom_path(aes(y = in_20, color = "in_20"), linewidth = 1) +
  geom_vline(xintercept = as.Date("2021-06-08")) +
  ylab("value") +
  ggtitle("Inpatient coefficents")

ggplot(june_coef, aes(x = issue_date)) +
  geom_path(aes(y = out_6, color = "out_6"), linewidth = 1) +
  geom_path(aes(y = out_13, color = "out_13"), linewidth = 1) +
  geom_path(aes(y = out_20, color = "out_20"), linewidth = 1) +
  geom_vline(xintercept = as.Date("2021-06-08")) +
  ggtitle("Outpatient Coefficents")


ggplot(june_coef, aes(x = issue_date)) +
  geom_path(aes(y = `(Intercept)`), linewidth = 1) +
  ggtitle("Intercept")

```



```{r}
contrib = june_coef %>%
  inner_join(ny_june_now, by = c("geo_value", "issue_date"),
             suffix = c("_coef", "")) %>%
  select(-window_date, -issue_date) %>%
  mutate(in_6 = in_6_coef * in_6,
         in_13 = in_13_coef * in_13,
         in_20 = in_20_coef * in_20,
         out_6 = out_6_coef * out_6,
         out_13 = out_13_coef * out_13,
         out_20 = out_20_coef * out_20,
         in_contrib = in_6+ in_13 + in_20,
         out_contrib = out_6 + out_13 + out_20) %>%
  select(-matches("_coef"))
```


```{r}
ggplot(contrib, aes(x = time_value)) +
  geom_path(aes(y = in_6, color = "in_6"), linewidth = 1) +
  geom_path(aes(y = in_13, color = "in_13"), linewidth = 1) +
  geom_path(aes(y = in_20, color = "in_20"), linewidth = 1) +
  geom_vline(xintercept = as.Date("2021-06-08")) +
  scale_y_continuous(limits = c(0, 0.6), breaks = scales::pretty_breaks(n = 5)) +
  ylab("value") +
  ggtitle("Inpatient, Real time: coefficent * signal")

ggplot(contrib, aes(x = time_value)) +
  geom_path(aes(y = out_6, color = "out_6"), linewidth = 1) +
  geom_path(aes(y = out_13, color = "out_13"), linewidth = 1) +
  geom_path(aes(y = out_20, color = "out_20"), linewidth = 1) +
  geom_vline(xintercept = as.Date("2021-06-08")) +
  ylab("value") +
  ggtitle("Outpatient, Real time: coefficent * signal")


ggplot(june_coef, aes(x = issue_date)) +
  geom_path(aes(y = `(Intercept)`), linewidth = 1) +
  ggtitle("Intercept")

```




```{r}
ny_train_feat = c()

for (i in c(as.Date("2021-04-30"), as.Date("2021-05-30"))) {
  for (j in seq(i, i + 30, by = 1))
  
  tmp = state_get_train_ar(i, j)
  
  ny_train_feat = rbind(ny_train_feat, tmp)
  
}
```



```{r}
ny_coef = state_model_coef %>% 
  filter(geo_value == "ny") 
  
ny_train_feat = ny_train_feat %>% filter(geo_value == "ny") %>%
  filter(time_value >= as.Date("2021-05-01")) %>%
  filter(issue_date == as.Date("2021-06-07") |
           issue_date == as.Date("2021-06-08")) %>%
  arrange(geo_value, time_value, issue_date)
```





```{r}
tmp = state_get_test_backnow_raw(as.Date(i), as.Date(j))
```


```{r}
ny_5 = ny_test_feat %>%
  filter(time_value <= as.Date("2021-05-31"))

ny_6 = ny_test_feat %>%
  filter(time_value > as.Date("2021-05-31"))


ny_p = lm(GT ~ in_6 + in_13 + in_20 + out_6 + out_13 + out_20, data = ny_5)
ny_n = lm(GT ~ in_6 + in_13 + in_20 + out_6 + out_13 + out_20, data = ny_6)
```



```{r}
m_6 = lm(GT ~ in_6 + in_13 + in_20 + out_6 + out_13 + out_20, data = ny_train_pos, 
         weights = exp(-0.0613 * backcast_lag))

m_7 = lm(GT ~ in_6 + in_13 + in_20 + out_6 + out_13 + out_20, data = ny_train_neg, 
         weights = exp(-0.0613 * backcast_lag))

```


```{r}
oracle_m = lm(GT ~ in_6 + in_13 + in_20 + out_6 + out_13 + out_20, data = ny_test_now)
```







```{r}
# ny_train_pos = ny_train_feat %>% filter(issue_date == as.Date("2021-06-07")) %>%
#   filter(geo_value == "ny")
# ny_train_neg = ny_train_feat %>% filter(issue_date == as.Date("2021-06-22")) %>%
#   filter(geo_value == "ny")
# 
# ny_merged = ny_train_pos %>%
#   inner_join(ny_train_neg, by = c("geo_value", "time_value"),
#              suffix = c("_pos", "_neg")) %>%
#   group_by(time_value) %>%
#   summarise(pdi_6 = (in_6_pos - in_6_neg) * 100 / in_6_pos,
#             pdi_13 = (in_13_pos - in_13_neg)* 100 / in_13_pos,
#             pdi_20 = (in_20_pos - in_20_neg) * 100/ in_20_pos,
#             pdo_6 = (out_6_pos - out_6_neg) * 100/ out_6_pos,
#             pdo_13 = (out_13_pos - out_13_neg) * 100/ out_13_pos,
#             pdo_20 = (out_20_pos - out_20_neg) * 100/ out_20_pos) %>%
#   filter(time_value >= as.Date("2021-05-01"))

```

