---
title: "err_stateonly_v_mixed"
author: "Xueda Shen, xs2"
date: "2023-08-23"
output: html_document
---


We plot figure 3 and 4 in this document. 


# Read data

```{r}
library(assertr)
library(comprehenr)
library(epidatr)
library(epiprocess)
library(broom)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggnewscale)
library(vroom)
library(simplecolors)
library(ggpubr)
library(eply)
library(colorspace)
```


```{r}
load("../RDS/err_stateonly_v_mixed.RData")
```



```{r}
vals = c("State-level" = "#E495A5", "Mixed Model" = "#86B875", "National Model" = "#7DB0DD")

ggplot(mae_state_rate) +
  geom_path(aes(x = backcast_lag, y = s_MAER, color = "State-level"), 
            size = 1, alpha = 0.4) +
  geom_ribbon(aes(x = backcast_lag, ymin = s_MAER - se, 
                  ymax= s_MAER + se, fill = "State-level"), 
              alpha = 0.4) +
  geom_path(data = mae_mixed_rate, aes(x = backcast_lag, y = m_MAER,
                color = "Mixed Model"), size = 1, alpha = 0.4) +
  geom_ribbon(data = mae_mixed_rate, aes(x = backcast_lag,
            ymin = m_MAER - se, 
            ymax = m_MAER + se,
            fill = "Mixed Model"),
            size = 1, alpha = 0.7) +
  geom_path(data = mae_national_rate, aes(x = backcast_lag, 
          y = n_MAER, color = "National Model"), size = 1, alpha = 0.4) +
  geom_ribbon(data = mae_national_rate, aes(x = backcast_lag,
            ymin = n_MAER - se, ymax = n_MAER + se,
            fill = "National Model"),
            size = 1, alpha = 0.7) +
  scale_color_manual(name = "", values = vals) +
  scale_fill_manual(name = "", values = vals) +
  scale_x_continuous(n.breaks = 6) +
  xlab("Backcast Lag") +
  ylab("MAE in Rate") +
  ylim(0.3, 0.6) +
  theme(legend.position = "bottom") +
  ggtitle("MAE in Rate, Monthly Update Period") 

ggsave("mixed_state_rate.pdf", width = 6, height = 4.5, dpi = 320)
```





```{r}
vals = c("State-level" = "#E495A5", "Mixed Model" = "#86B875", "National Model" = "#7DB0DD")

ggplot(mae_state_count) +
  geom_path(aes(x = backcast_lag, y = sMAE, color = "State-level"), 
            size = 1, alpha = 0.4) +
  geom_ribbon(aes(x = backcast_lag, ymin = sMAE - se, 
                  ymax= sMAE + se, fill = "State-level"), 
              alpha = 0.4) +
  geom_path(data = mae_mixed_count, aes(x = backcast_lag, y = mMAE,
                color = "Mixed Model"), size = 1, alpha = 0.4) +
  geom_ribbon(data = mae_mixed_count, aes(x = backcast_lag,
            ymin = mMAE - se, 
            ymax = mMAE + se,
            fill = "Mixed Model"),
            size = 1, alpha = 0.7) +
  geom_path(data = mae_national_count, aes(x = backcast_lag, 
            y = nMAE, color = "National Model"),
            size = 1, alpha = 0.4) +
  geom_ribbon(data = mae_national_count, aes(x = backcast_lag,
            ymin = nMAE - se,
            ymax = nMAE + se,
            fill = "National Model"),
            size = 1, alpha = 0.4) +
  scale_color_manual(name = "", values = vals) +
  scale_fill_manual(name = "", values = vals) +
  scale_x_continuous(n.breaks = 6) +
  xlab("Backcast Lag") +
  ylab("MAE in Counts") +
  theme(legend.position = "bottom") +
  ggtitle("MAE in Counts, Monthly Update Period") 

ggsave("mixed_state_count.pdf", width = 6, height = 4.5, dpi = 320)
```
