---
title: "holdin_vis"
author: "Xueda Shen, xs2"
date: "2023-06-26"
output: html_document
---

# Purpose

We produce figure 5 and 6 in this document.



# Read data

```{r}
library(ggpubr)
library(vroom)
library(tidyverse)
```

# Big Lag

```{r}
us_pop = covidcast::state_census %>%
          select(ABBR, POPESTIMATE2019) %>%
          rename(geo_value = ABBR) %>%
          rename(pop = POPESTIMATE2019) %>%
          mutate(geo_value = tolower(geo_value)) %>%
          filter(!geo_value %in% c("as", "gu", "mp", "pr", "vi"))


bl_uncon_pred = vroom("../../predictions/bl_versioned_hhs_mixed.csv") %>%
  filter(time_value <= as.Date("2021-12-01")) %>%
  inner_join(us_pop, by = "geo_value") %>%
  mutate(backcast_lag = as.numeric(issue_date - time_value)) %>%
  rowwise() %>%
  mutate(state_fit = max(0, state_fit)) %>%
  mutate(national_fit = max(0, national_fit)) %>%
  mutate(GT_norm_back = GT * pop / 10^5) %>%
  mutate(national_fit_back = national_fit * pop / 10^5) %>%
  mutate(state_fit_back = state_fit * pop / 10^5) %>%
  select(geo_value, time_value, issue_date, backcast_lag, optimal, staleness, 
         GT, state_fit, national_fit, GT_norm_back, state_fit_back, national_fit_back) %>%
  inner_join(us_pop, by = "geo_value")


bl_nowcasts = bl_uncon_pred %>%
  filter(backcast_lag == 0)

bl_backcasts = bl_uncon_pred %>%
  filter(backcast_lag == 5)

```

# Paper plot, nowcasts 

## Nowcasts and Backcasts, big states

```{r}
big_vis = c("ca", "tx")
smaller_vis = c("ky", "vt")


colrs = c("State-wise" = "#39BEB1")
fills = c("Actual Hospitalizations" = "#8B8B8B")
lty = c("Nowcasts" = "solid", "Backcasts" = "twodash")
```



```{r}

big_pl = c()

for (state in big_vis) {

  data_bl = bl_nowcasts %>%
    filter(geo_value == state)
  
  data_bl_back = bl_backcasts %>% 
    filter(geo_value == state)
  
    p1 = ggplot(data_bl, aes(x = time_value, y = GT_norm_back)) +
        geom_bar(stat = "identity", aes(fill = "Actual Hospitalizations")) +
        scale_x_date(date_labels = "%b", date_breaks = "1 month") +
        xlab("Date") +
        ylab("Hospitalizations") +
        geom_path(aes(x = time_value, y = state_fit_back, 
                      color = "Nowcasts", linetype = "Nowcasts"),
                  size = 1) +
        geom_path(data = data_bl_back, aes(x = time_value, 
                  y = state_fit_back, color = "Backcasts",
                  linetype = "Backcasts"),
                  size = 1, alpha = 0.8) +
        scale_fill_manual(name = "", 
                          values = c("Actual Hospitalizations" = "#8B8B8B")) +
        scale_color_manual(name = "",
                           values = c("Nowcasts" = "#39BEB1", "Backcasts" = "#E495A5"),
                           guide = guide_legend(override.aes = list(fill = NULL, 
                                                                    linetype = c("solid", "twodash")))) +
        scale_linetype_manual(name = "",
                              values = c("Nowcasts" = "solid", "Backcasts" = "twodash"),
                              guide = "legend") +
        theme(legend.position = "bottom") +
        ggtitle(paste0(toupper(state), " , Nowcasts and Backcasts at Lag 5, State-wise Model"))
  

  big_pl = append(big_pl, list(p1)) 
}

ggarrange(plotlist = big_pl, nrow = 2, common.legend = TRUE, legend = "bottom")

# ggsave("stateonly_now_back_big.pdf", width = 6, height = 4.5, dpi = 320)
```


## Nowcasts + Backcasts, smaller states

```{r}

smaller_pl = c()

for (state in smaller_vis) {
  

  
  data_bl = bl_nowcasts %>%
    filter(geo_value == state)
  
  data_bl_back = bl_backcasts %>% 
    filter(geo_value == state)
  
  p1 = ggplot(data_bl, aes(x = time_value, y = GT_norm_back)) +
        geom_bar(stat = "identity", aes(fill = "Actual Hospitalizations")) +
        scale_x_date(date_labels = "%b", date_breaks = "1 month") +
        xlab("Date") +
        ylab("Hospitalizations") +
        geom_path(aes(x = time_value, y = state_fit_back, 
                      color = "Nowcasts", linetype = "Nowcasts"),
                  size = 1) +
        geom_path(data = data_bl_back, aes(x = time_value, 
                  y = state_fit_back, color = "Backcasts",
                  linetype = "Backcasts"),
                  size = 1, alpha = 0.8) +
        scale_fill_manual(name = "", 
                          values = c("Actual Hospitalizations" = "#8B8B8B")) +
        scale_color_manual(name = "",
                           values = c("Nowcasts" = "#39BEB1", "Backcasts" = "#E495A5"),
                           guide = guide_legend(override.aes = list(fill = NULL, 
                                                                    linetype = c("solid", "twodash")))) +
        scale_linetype_manual(name = "",
                              values = c("Nowcasts" = "solid", "Backcasts" = "twodash"),
                              guide = "legend") +
        theme(legend.position = "bottom") +
        ggtitle(paste0(toupper(state), " , Nowcasts and Backcasts at Lag 5, State-wise Model"))

  smaller_pl = append(smaller_pl, list(p1)) 
}

ggarrange(plotlist = smaller_pl, nrow = 2, common.legend = TRUE, legend = "bottom")
# ggsave("stateonly_now_back_smaller.pdf", width = 6, height = 4.5, dpi = 320)
```

