---
title: "baseline_coverage"
output: html_document
date: "2024-05-16"
---

# Purpose

We visualize the interval of QT, sample quantiles (weighted, unweighted). 

```{r, message=FALSE}
library(tidyverse)
library(vroom)

uspop = covidcast::state_census %>%
  select(ABBR, POPESTIMATE2019) %>%
  rename(geo_value = ABBR) %>%
  rename(pop = POPESTIMATE2019) %>%
  mutate(geo_value = tolower(geo_value)) %>%
  slice(., 2:(n() - 4))
```

```{r}
list_intervals = readRDS("../predictions/quanTrack_Baseline.rds")

state_QT = list_intervals[[1]]; unweighted_frame = list_intervals[[2]]; weighted_frame = list_intervals[[3]]

state_QT = state_QT %>%
  mutate(backcast_lag = as.numeric(issue_date - time_value))
unweighted_frame = unweighted_frame %>%
  mutate(backcast_lag = as.numeric(issue_date - time_value))
weighted_frame = weighted_frame %>%
  mutate(backcast_lag = as.numeric(issue_date - time_value))

state_QT_2 = state_QT %>%
  filter(alpha == 0.2)
state_QT_4 = state_QT %>%
  filter(alpha == 0.4)

unweighted_2 = unweighted_frame %>%
  filter(alpha == 0.2)
unweighted_4 = unweighted_frame %>%
  filter(alpha == 0.4)

weighted_2 = weighted_frame %>%
  filter(alpha == 0.2)
weighted_4 = weighted_frame %>%
  filter(alpha == 0.4)


```


```{r}
dump_dates = c(as.Date("2021-04-01"), as.Date("2021-05-01"), as.Date("2021-06-01"), 
              as.Date("2021-07-01"), as.Date("2021-08-01"), as.Date("2021-09-01"),
              as.Date("2021-10-01"), as.Date("2021-11-01"), as.Date("2021-12-01"))


qt_2_scores = state_QT_2 %>%
  group_by(geo_value) %>%
  filter(issue_date %in% dump_dates) %>%
  filter(time_value == issue_date) %>%
  select(geo_value, time_value, lower_score, upper_score)


unwei_2_scores = unweighted_2 %>%
  group_by(geo_value) %>%
  filter(issue_date %in% dump_dates) %>%
  filter(time_value == issue_date) %>%
  select(geo_value, time_value, lower_q, upper_q)

wei_2_scores = weighted_2 %>%
  group_by(geo_value) %>%
  filter(issue_date %in% dump_dates) %>%
  filter(time_value == issue_date) %>%
  select(geo_value, time_value, lower_q, upper_q)
```




# Visualizations

```{r}
cbPalette = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442",
              "#0072B2", "#D55E00", "#CC79A7")
fills = c("Actual Hospitalizations" = cbPalette[1], "Unweighted" = cbPalette[6],
          "QT" = cbPalette[2], "Weighted" = cbPalette[4])
cols = c("Nowcasts" = cbPalette[6])
states = unique(weighted_2$geo_value)


for (s in states) {
  
  unwei_state = unweighted_2 %>%
    filter(geo_value == s) %>%
    filter(time_value == issue_date) %>%
    filter(time_value <= as.Date("2021-12-01"))
  
  quant_state = state_QT_2 %>%
    filter(geo_value == s) %>%
    filter(time_value == issue_date) %>%
    filter(time_value <= as.Date("2021-12-01"))
  
  wei_state = weighted_2 %>%
    filter(geo_value == s) %>%
    filter(time_value == issue_date) %>%
    filter(time_value <= as.Date("2021-12-01"))

  p1 = ggplot(unwei_state, aes(x = time_value, y = GT)) +
    geom_bar(stat = "identity", aes(fill = "Actual Hospitalizations"), alpha = 0.7) +
    geom_line(aes(x = time_value, y = state_fit, color = "Unweighted")) +
    geom_ribbon(aes(x = time_value, ymin = lower, ymax = upper, fill = "Unweighted"), alpha = 0.4) +
    # geom_line(data = quant_state, aes(x = time_value, y = state_fit, color = "QT")) +
    # geom_ribbon(data = quant_state, aes(x = time_value, ymin = lower,
    #   ymax = upper, fill = "QT"), alpha = 0.4) +
    geom_line(data = wei_state, aes(x = time_value, y = state_fit, color = "Weighted")) +
    geom_ribbon(data = wei_state, aes(x = time_value, ymin = lower,
      ymax = upper, fill = "Weighted"), alpha = 0.4) +
    scale_color_manual(name = "", values = fills) +
    scale_fill_manual(name = "", values = fills) +
    scale_x_date(date_breaks = "1 month", expand = c(0.01, 0.05),
                 labels = scales::label_date_short()) +
    xlab("Date") +
    ylab("Hospitalization rate") +
    theme_bw() +
    theme(legend.position = "bottom") +
    ggtitle(paste0(toupper(s), ", alpha = 0.2"))
    
  print(p1)
  
}

```



```{r}
cbPalette = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442",
              "#0072B2", "#D55E00", "#CC79A7")
fills = c("Actual Hospitalizations" = cbPalette[1], "Unweighted" = cbPalette[6],
          "QT" = cbPalette[2], "Weighted" = cbPalette[4])
cols = c("Nowcasts" = cbPalette[6])
states = unique(weighted_2$geo_value)


for (s in states) {
  
  unwei_state = unweighted_4 %>%
    filter(geo_value == s) %>%
    filter(time_value == issue_date) %>%
    filter(time_value <= as.Date("2021-12-01"))
  
  quant_state = state_QT_4 %>%
    filter(geo_value == s) %>%
    filter(time_value == issue_date) %>%
    filter(time_value <= as.Date("2021-12-01"))
  
  wei_state = weighted_4 %>%
    filter(geo_value == s) %>%
    filter(time_value == issue_date) %>%
    filter(time_value <= as.Date("2021-12-01"))

  p1 = ggplot(unwei_state, aes(x = time_value, y = GT)) +
    geom_bar(stat = "identity", aes(fill = "Actual Hospitalizations"), alpha = 0.7) +
    geom_line(aes(x = time_value, y = state_fit, color = "Unweighted")) +
    geom_ribbon(aes(x = time_value, ymin = lower, ymax = upper, fill = "Unweighted"), alpha = 0.4) +
    geom_line(data = quant_state, aes(x = time_value, y = state_fit, color = "QT")) +
    geom_ribbon(data = quant_state, aes(x = time_value, ymin = lower,
      ymax = upper, fill = "QT"), alpha = 0.4) +
    geom_line(data = wei_state, aes(x = time_value, y = state_fit, color = "Weighted")) +
    geom_ribbon(data = wei_state, aes(x = time_value, ymin = lower, 
      ymax = upper, fill = "Weighted"), alpha = 0.4) +
    scale_color_manual(name = "", values = fills) +
    scale_fill_manual(name = "", values = fills) +
    scale_x_date(date_breaks = "1 month", expand = c(0.01, 0.05),
                 labels = scales::label_date_short()) +
    xlab("Date") +
    ylab("Hospitalization rate") +
    theme_bw() +
    theme(legend.position = "bottom") +
    ggtitle(paste0(toupper(s), ", alpha = 0.4"))
    
  print(p1)
  
}

```




# Nowcasts vs backcasts


```{r}
cbPalette = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442",
              "#0072B2", "#D55E00", "#CC79A7")
fills = c("Actual Hospitalizations" = cbPalette[1], "Nowcasts" = cbPalette[6],
          "Backcasts at lag 10" = cbPalette[2])
cols = c("Nowcasts" = cbPalette[6])
states = unique(weighted_2$geo_value)


for (s in states) {

  quant_now = state_QT_2 %>%
    filter(geo_value == s) %>%
    filter(time_value == issue_date) %>%
    filter(time_value <= as.Date("2021-12-01"))

  
  quant_back = state_QT_2 %>%
    filter(geo_value == s) %>%
    filter(issue_date == time_value + 10) %>%
    filter(time_value <= as.Date("2021-12-01"))
  
  
  p1 = ggplot(quant_now, aes(x = time_value, y = GT)) +
    geom_bar(stat = "identity", aes(fill = "Actual Hospitalizations"), alpha = 0.7) +
    geom_line(aes(x = time_value, y = state_fit, color = "Nowcasts")) +
    geom_ribbon(aes(x = time_value, ymin = lower, ymax = upper, fill = "Nowcasts"), alpha = 0.4) +
    geom_line(data = quant_back, aes(x = time_value, y = state_fit, color = "Backcasts at lag 10")) +
    geom_ribbon(data = quant_back, aes(x = time_value, ymin = lower,
      ymax = upper, fill = "Backcasts at lag 10"), alpha = 0.4) +
    scale_color_manual(name = "", values = fills) +
    scale_fill_manual(name = "", values = fills) +
    scale_x_date(date_breaks = "1 month", expand = c(0.01, 0.05),
                 labels = scales::label_date_short()) +
    xlab("Date") +
    ylab("Hospitalization rate") +
    theme_bw() +
    theme(legend.position = "bottom") +
    ggtitle(paste0(toupper(s), ", alpha = 0.2"))
    
  print(p1)
  
}

```
